### ISSUE TITLE
Cannot install frida-node on mac

### ISSUE THREAD

**Issue by ballballsun** [frida/frida-node#17]
Hi, me again, After I install frida, I can use python to debug process. But when I reading and trying the demos, ZeroNights2015. Most of them are written in javascript, so I installed Node.js and going to try the demo.

```
const frida = require('frida');
const load = require('frida-load');
const co = require('co');
```
got Error: Cannot find module 'frida'

Then I believe that frida-node is needed, so I try to get the module from that. But got the following error:
```
$ npm install

> frida@0.0.0 install frida-master/frida-node
> prebuild --install

  CXX(target) Release/obj.target/frida_binding/src/addon.o
In file included from ../src/addon.cc:1:
In file included from ../src/application.h:4:
In file included from ../src/glib_object.h:4:
In file included from ../src/runtime.h:4:
../src/glib_context.h:4:10: fatal error: 'frida-core.h' file not found
#include <frida-core.h>
         ^
1 error generated.
make: *** [Release/obj.target/frida_binding/src/addon.o] Error 1
prebuild ERR! build error 
prebuild ERR! stack Error: `make` failed with exit code: 2
prebuild ERR! stack     at ChildProcess.onExit (frida-master/frida-node/node_modules/node-gyp/lib/build.js:276:23)
prebuild ERR! stack     at emitTwo (events.js:100:13)
prebuild ERR! stack     at ChildProcess.emit (events.js:185:7)
prebuild ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
prebuild ERR! not ok 
prebuild ERR! build Error: `make` failed with exit code: 2
prebuild ERR! build     at ChildProcess.onExit (frida-master/frida-node/node_modules/node-gyp/lib/build.js:276:23)
prebuild ERR! build     at emitTwo (events.js:100:13)
prebuild ERR! build     at ChildProcess.emit (events.js:185:7)
prebuild ERR! build     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)

npm ERR! Darwin 15.2.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install"
npm ERR! node v5.5.0
npm ERR! npm  v3.5.3
npm ERR! code ELIFECYCLE
npm ERR! frida@0.0.0 install: `prebuild --install`
npm ERR! Exit status 2
npm ERR! 
npm ERR! Failed at the frida@0.0.0 install script 'prebuild --install'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the frida package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     prebuild --install
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs frida
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls frida
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     frida-master/frida-node/npm-debug.log
```

Wish your kind help :)

**Comment by SomeoneWeird** [comment]
Is there a reason you're installing from source? You should just be able to download a pre-compiled version of the addon using `npm install frida`

**Comment by ballballsun** [comment]
Thx for reply. Because I am not familiar with node.js, and the command line very much. I just follow the instruction from frida-node, https://github.com/frida/frida-node, at the bottom.

No idea on the difference of `npm install` and `npm install frida`. But I will try it on the coming Monday. Thx :)

**Comment by dweinstein** [comment]
try using `$ npm install --save frida@latest` then `$ npm install` in your directory again.

**Comment by ballballsun** [comment]
Ok thx! work now :)

**Comment by illnino** [comment]
Hi, there

I tried to install via `npm install frida`, but I got the same error. May you please check?

OS: Mac: 10.11.6


```
prebuild info spawn args [ 'V=1', 'BUILDTYPE=Release', '-C', 'build' ]
In file included from ../src/addon.cc:1:
In file included from ../src/application.h:4:
In file included from ../src/glib_object.h:4:
In file included from ../src/runtime.h:4:
../src/glib_context.h:4:10: fatal error: 'frida-core.h' file not found
#include <frida-core.h>
         ^
1 error generated.
make: *** [Release/obj.target/frida_binding/src/addon.o] Error 1
prebuild ERR! build error
prebuild ERR! stack Error: `make` failed with exit code: 2
prebuild ERR! stack     at ChildProcess.onExit (/Users/its/Project/tools/frida/node_modules/frida/node_modules/prebuild/node_modules/node-gyp/lib/build.js:276:23)
prebuild ERR! stack     at emitTwo (events.js:87:13)
prebuild ERR! stack     at ChildProcess.emit (events.js:172:7)
prebuild ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
prebuild ERR! not ok
prebuild ERR! build Error: `make` failed with exit code: 2
prebuild ERR! build     at ChildProcess.onExit (/Users/its/Project/tools/frida/node_modules/frida/node_modules/prebuild/node_modules/node-gyp/lib/build.js:276:23)
prebuild ERR! build     at emitTwo (events.js:87:13)
prebuild ERR! build     at ChildProcess.emit (events.js:172:7)
prebuild ERR! build     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
npm verb unsafe-perm in lifecycle true
npm info frida@8.2.2 Failed to exec install script
npm verb unlock done using /Users/its/.npm/_locks/frida-a7db794772f089b4.lock for /Users/its/Project/tools/frida/node_modules/frida
npm verb stack Error: frida@8.2.2 install: `prebuild --install`
npm verb stack Exit status 2
npm verb stack     at EventEmitter.<anonymous> (/Users/its/.nvm/versions/node/v4.5.0/lib/node_modules/npm/lib/utils/lifecycle.js:217:16)
npm verb stack     at emitTwo (events.js:87:13)
npm verb stack     at EventEmitter.emit (events.js:172:7)
npm verb stack     at ChildProcess.<anonymous> (/Users/its/.nvm/versions/node/v4.5.0/lib/node_modules/npm/lib/utils/spawn.js:24:14)
npm verb stack     at emitTwo (events.js:87:13)
npm verb stack     at ChildProcess.emit (events.js:172:7)
npm verb stack     at maybeClose (internal/child_process.js:829:16)
npm verb stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
npm verb pkgid frida@8.2.2
npm verb cwd /Users/its/Project/tools/frida
npm ERR! Darwin 15.6.0
npm ERR! argv "/Users/its/.nvm/versions/node/v4.5.0/bin/node" "/Users/its/.nvm/versions/node/v4.5.0/bin/npm" "install" "frida" "--verbose"
npm ERR! node v4.5.0
npm ERR! npm  v2.15.9
npm ERR! code ELIFECYCLE

npm ERR! frida@8.2.2 install: `prebuild --install`
npm ERR! Exit status 2
npm ERR!
npm ERR! Failed at the frida@8.2.2 install script 'prebuild --install'.
npm ERR! This is most likely a problem with the frida package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     prebuild --install
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs frida
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!
npm ERR!     npm owner ls frida
npm ERR! There is likely additional logging output above.
npm verb exit [ 1, true ]
npm verb unbuild node_modules/frida
npm info preuninstall frida@8.2.2
npm info uninstall frida@8.2.2
npm verb unbuild rmStuff frida@8.2.2 from /Users/its/Project/tools/frida/node_modules
npm info postuninstall frida@8.2.2
npm verb gentlyRm don't care about contents; nuking /Users/its/Project/tools/frida/node_modules/frida

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/its/Project/tools/frida/npm-debug.log
```
