### ISSUE TITLE
Invalid ELF header in `10.6.24`

### ISSUE THREAD

**Issue by brendonjohn** [frida/frida-node#26]
Hey Ole,

I love your work with Frida. 

I think there's an issue with the recent patch 4 days ago.

Environment: Debian OS.

```
/source/node_modules/bindings/bindings.js:88
        throw e
        ^

Error: /source/node_modules/frida/build/Release/frida_binding.node: invalid ELF header
    at Object.Module._extensions..node (module.js:653:18)
    at Module.load (module.js:545:32)
    at tryModuleLoad (module.js:508:12)
    at Function.Module._load (module.js:500:3)
    at Module.require (module.js:568:17)
    at require (internal/module.js:11:18)
    at bindings (/source/node_modules/bindings/bindings.js:81:44)
    at Object.<anonymous> (/source/node_modules/frida/lib/frida.js:56:34)
    at Module._compile (module.js:624:30)
    at Object.Module._extensions..js (module.js:635:10)
```

**Comment by brendonjohn** [comment]
mmmm... I think this is a local issue, apologies.
