### ISSUE TITLE
npm install fails on macOS

### ISSUE THREAD

**Issue by tosbaha** [frida/frida-node#42]
I use Node v11.11.0 on macOS Mojave. Doing npm i frida gives below error

> frida@12.6.1 install /Users/mustafa/Downloads/mplus-master/node_modules/frida
> prebuild-install || node-gyp rebuild

```
prebuild-install WARN install No prebuilt binaries found (target=11.11.0 runtime=node arch=x64 libc= platform=darwin)
gyp: binding.gyp not found (cwd: /Users/mustafa/Downloads/mplus-master/node_modules/frida) while trying to load binding.gyp
gyp ERR! configure error
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:345:16)
gyp ERR! stack     at ChildProcess.emit (events.js:197:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:254:12)
gyp ERR! System Darwin 18.6.0
gyp ERR! command "/usr/local/Cellar/node/11.11.0/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/mustafa/Downloads/mplus-master/node_modules/frida
gyp ERR! node -v v11.11.0
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! frida@12.6.1 install: `prebuild-install || node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the frida@12.6.1 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/mustafa/.npm/_logs/2019-05-28T21_15_38_202Z-debug.log
```

**Comment by oleavr** [comment]
We currently only provide prebuilt binaries for Node.js 8, 10, and 12. Recommend upgrading to 12.
