### ISSUE TITLE
issue  building 

### ISSUE THREAD

**Issue by a-gamer** [frida/frida-node#84]
i get error when trying building  frida

gyp: binding.gyp not found (cwd: /data/data/com.termux/files/home/node_modules/frida) while trying to load binding.gyp
gyp ERR! configure error ify:@frida/nan: timing reifyNo gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/data/data/com.termux/files/home/node_modules/node-gyp/lib/configure.js:325:16)                                            gyp ERR! stack     at ChildProcess.emit (node:events:513:28)                                                    gyp ERR! stack     at ChildProcess._handle.onexit (node:internal/child_process:291:12)                          gyp ERR! System Linux 4.14.180-perf-gd3e8272ae7d0
gyp ERR! command "/data/data/com.termux/files/usr/bin/node" "/data/data/com.termux/files/home/node_modules/.bin/node-gyp" "rebuild"
gyp ERR! cwd /data/data/com.termux/files/home/node_modules/frida
gyp ERR! node -v v18.12.1
gyp ERR! node-gyp -v v9.3.1                             gyp ERR! not ok
npm ERR! code 1
npm ERR! path /data/data/com.termux/files/home/node_modules/frida                                               npm ERR! command failed
npm ERR! command sh -c prebuild-install || node-gyp rebuild

**Comment by liudonghua123** [comment]
same problems (binding.gyp not found) when install `wechaty-puppet-xp@next`.

<details><summary>Details</summary>

```
Liu.D.H  puppet-xp-getting-started  git(main)   9ms  14:20 > npm i wechaty-puppet-xp@next -S
npm warn deprecated inflight@1.0.6: This module is not supported, and leaks memory. Do not use it. Check out lru-cache if you want a good and tested way to coalesce async requests by a key value, which is much more comprehensive and powerful.
npm warn deprecated lodash.pick@4.4.0: This package is deprecated. Use destructuring assignment syntax instead.
npm warn deprecated phin@2.9.3: Package no longer supported. Contact Support at https://www.npmjs.com/support for more info.
npm warn deprecated lodash.get@4.4.2: This package is deprecated. Use the optional chaining (?.) operator instead.
npm warn deprecated @humanwhocodes/config-array@0.13.0: Use @eslint/config-array instead
npm warn deprecated @hapi/pinpoint@1.0.2: Moved to 'npm install @sideway/pinpoint'
npm warn deprecated @hapi/topo@3.1.6: This version has been deprecated and is no longer supported or maintained
npm warn deprecated level-concat-iterator@3.1.0: Superseded by abstract-level (https://github.com/Level/community#faq)
npm warn deprecated level-errors@3.0.1: Superseded by abstract-level (https://github.com/Level/community#faq)
npm warn deprecated encoding-down@7.1.0: Superseded by abstract-level (https://github.com/Level/community#faq)
npm warn deprecated har-validator@5.1.5: this library is no longer supported
npm warn deprecated rimraf@3.0.2: Rimraf versions prior to v4 are no longer supported
npm warn deprecated glob@8.0.3: Glob versions prior to v9 are no longer supported
npm warn deprecated glob@7.2.3: Glob versions prior to v9 are no longer supported
npm warn deprecated glob@7.2.3: Glob versions prior to v9 are no longer supported
npm warn deprecated glob@7.2.3: Glob versions prior to v9 are no longer supported
npm warn deprecated glob@7.2.3: Glob versions prior to v9 are no longer supported
npm warn deprecated glob@7.2.3: Glob versions prior to v9 are no longer supported
npm warn deprecated @hapi/formula@1.2.0: Moved to 'npm install @sideway/formula'
npm warn deprecated @humanwhocodes/object-schema@2.0.3: Use @eslint/object-schema instead
npm warn deprecated level-codec@10.0.0: Superseded by level-transcoder (https://github.com/Level/community#faq)
npm warn deprecated deferred-leveldown@7.0.0: Superseded by abstract-level (https://github.com/Level/community#faq)
npm warn deprecated levelup@5.1.1: Superseded by abstract-level (https://github.com/Level/community#faq)
npm warn deprecated level-packager@6.0.1: Superseded by abstract-level (https://github.com/Level/community#faq)
npm warn deprecated @hapi/address@2.1.4: Moved to 'npm install @sideway/address'
npm warn deprecated level-js@6.1.0: Superseded by browser-level (https://github.com/Level/community#faq)
npm warn deprecated cuid@2.1.8: Cuid and other k-sortable and non-cryptographic ids (Ulid, ObjectId, KSUID, all UUIDs) are all insecure. Use @paralleldrive/cuid2 instead.
npm warn deprecated uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
npm warn deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
npm warn deprecated @hapi/hoek@8.5.1: This version has been deprecated and is no longer supported or maintained
npm warn deprecated abstract-leveldown@7.2.0: Superseded by abstract-level (https://github.com/Level/community#faq)
npm warn deprecated @hapi/joi@16.1.8: Switch to 'npm install joi'
npm warn deprecated sinon@13.0.2: 16.1.1
npm warn deprecated leveldown@6.1.1: Superseded by classic-level (https://github.com/Level/community#faq)
npm warn deprecated eslint@8.57.1: This version is no longer supported. Please see https://eslint.org/version-support for other options.
npm error code 1
npm error path D:\code\node\puppet-xp-getting-started\node_modules\frida
npm error command failed
npm error command C:\WINDOWS\system32\cmd.exe /d /s /c prebuild-install || node-gyp rebuild
npm error prebuild-install warn install No prebuilt binaries found (target=20.18.0 runtime=node arch=x64 libc= platform=win32)
npm error gyp info it worked if it ends with ok
npm error gyp info using node-gyp@10.1.0
npm error gyp info using node@20.18.0 | win32 | x64
npm error gyp info find Python using Python version 3.13.0 found at "C:\Users\Liu.D.H\AppData\Local\Programs\Python\Python313\python3.13t.exe"
npm error gyp info find VS using VS2022 (17.12.35527.113) found at:
npm error gyp info find VS "C:\Program Files\Microsoft Visual Studio\2022\Community"
npm error gyp info find VS run with --verbose for detailed information
npm error gyp info spawn C:\Users\Liu.D.H\AppData\Local\Programs\Python\Python313\python3.13t.exe
npm error gyp info spawn args [
npm error gyp info spawn args 'C:\\Users\\Liu.D.H\\AppData\\Roaming\\nvm\\v20.18.0\\node_modules\\npm\\node_modules\\node-gyp\\gyp\\gyp_main.py',
npm error gyp info spawn args 'binding.gyp',
npm error gyp info spawn args '-f',
npm error gyp info spawn args 'msvs',
npm error gyp info spawn args '-I',
npm error gyp info spawn args 'D:\\code\\node\\puppet-xp-getting-started\\node_modules\\frida\\build\\config.gypi',
npm error gyp info spawn args '-I',
npm error gyp info spawn args 'C:\\Users\\Liu.D.H\\AppData\\Roaming\\nvm\\v20.18.0\\node_modules\\npm\\node_modules\\node-gyp\\addon.gypi',
npm error gyp info spawn args '-I',
npm error gyp info spawn args 'C:\\Users\\Liu.D.H\\AppData\\Local\\node-gyp\\Cache\\20.18.0\\include\\node\\common.gypi',
npm error gyp info spawn args '-Dlibrary=shared_library',
npm error gyp info spawn args '-Dvisibility=default',
npm error gyp info spawn args '-Dnode_root_dir=C:\\Users\\Liu.D.H\\AppData\\Local\\node-gyp\\Cache\\20.18.0',
npm error gyp info spawn args '-Dnode_gyp_dir=C:\\Users\\Liu.D.H\\AppData\\Roaming\\nvm\\v20.18.0\\node_modules\\npm\\node_modules\\node-gyp',
npm error gyp info spawn args '-Dnode_lib_file=C:\\\\Users\\\\Liu.D.H\\\\AppData\\\\Local\\\\node-gyp\\\\Cache\\\\20.18.0\\\\<(target_arch)\\\\node.lib',
npm error gyp info spawn args '-Dmodule_root_dir=D:\\code\\node\\puppet-xp-getting-started\\node_modules\\frida',
npm error gyp info spawn args '-Dnode_engine=v8',
npm error gyp info spawn args '--depth=.',
npm error gyp info spawn args '--no-parallel',
npm error gyp info spawn args '--generator-output',
npm error gyp info spawn args 'D:\\code\\node\\puppet-xp-getting-started\\node_modules\\frida\\build',
npm error gyp info spawn args '-Goutput_dir=.'
npm error gyp info spawn args ]
npm error gyp: binding.gyp not found (cwd: D:\code\node\puppet-xp-getting-started\node_modules\frida) while trying to load binding.gyp
npm error gyp ERR! configure error
npm error gyp ERR! stack Error: `gyp` failed with exit code: 1
npm error gyp ERR! stack at ChildProcess.<anonymous> (C:\Users\Liu.D.H\AppData\Roaming\nvm\v20.18.0\node_modules\npm\node_modules\node-gyp\lib\configure.js:297:18)
npm error gyp ERR! stack at ChildProcess.emit (node:events:519:28)
npm error gyp ERR! stack at ChildProcess._handle.onexit (node:internal/child_process:294:12)
npm error gyp ERR! System Windows_NT 10.0.26100
npm error gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\Liu.D.H\\AppData\\Roaming\\nvm\\v20.18.0\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
npm error gyp ERR! cwd D:\code\node\puppet-xp-getting-started\node_modules\frida
npm error gyp ERR! node -v v20.18.0
npm error gyp ERR! node-gyp -v v10.1.0
npm error gyp ERR! not ok
npm error A complete log of this run can be found in: C:\Users\Liu.D.H\AppData\Local\npm-cache\_logs\2025-09-04T06_21_08_132Z-debug-0.log

Liu.D.H  puppet-xp-getting-started  git(main)   2m 53.607s  14:24 >
```

</details>
